<!DOCTYPE html>
<html lang="en"><head>
<script src="w4-1-ols_files/libs/clipboard/clipboard.min.js"></script>
<script src="w4-1-ols_files/libs/quarto-html/tabby.min.js"></script>
<script src="w4-1-ols_files/libs/quarto-html/popper.min.js"></script>
<script src="w4-1-ols_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="w4-1-ols_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="w4-1-ols_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="w4-1-ols_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Davide Proserpio">
  <title>Regression: Modeling Relationships</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="w4-1-ols_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="w4-1-ols_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="w4-1-ols_files/libs/revealjs/dist/theme/quarto-80bfa77cf879cdeec7850b9befca25f7.css">
  <link href="w4-1-ols_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="w4-1-ols_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="w4-1-ols_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="w4-1-ols_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Regression: Modeling Relationships</h1>
  <p class="subtitle">MKT 566 · Fall 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Davide Proserpio
</div>
        <p class="quarto-title-affiliation">
            USC Marshall School of Business
          </p>
    </div>
</div>

</section>
<section>
<section id="before-we-start" class="title-slide slide level1 divider center">
<h1>Before We Start</h1>

</section>
<section id="housekeeping" class="slide level2">
<h2>Housekeeping</h2>
<ul>
<li>The <strong>RateBeer report</strong> (<code>ratebeer-report.html</code> + <code>ai-log.md</code>) is due <strong>Sunday, Sept.&nbsp;20, 11:59 pm</strong> on Brightspace</li>
<li><strong>Homework 2</strong> is released today and due <strong>Thursday, Oct.&nbsp;8</strong>. It covers today (OLS) and Tuesday (logit), on a box-office dataset</li>
<li><strong>Group project</strong>: proposal presentations are on <strong>Oct.&nbsp;13 and 15</strong> (10–15 minutes per group: the problem you will study and how)</li>
<li>Tuesday: <strong>logit</strong>, then the <strong>Airbnb exercise</strong> on your laptop</li>
</ul>
</section>
<section id="from-charts-to-models" class="slide level2 smaller-90">
<h2>From charts to models</h2>
<p>Last week you <em>looked</em> at how two variables move together. Today you put a <strong>number</strong> on it, and learn to tell when that number can be trusted.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Today you learn to</strong></p>
<ol type="1">
<li>Say what a regression <strong>is</strong> (a line, chosen a specific way)</li>
<li><strong>Read</strong> R’s output: coefficient, standard error, p-value, R²</li>
<li><strong>Interpret</strong> a coefficient in business units, with and without logs</li>
<li>Handle <strong>categorical</strong> predictors (city, room type)</li>
</ol>
</div><div class="column" style="width:50%;">
<p><strong>What stays the same</strong></p>
<ul>
<li>The AI writes the code. You choose the model, and you read the result</li>
<li>Two habits: <strong>predict</strong> before you run, <strong>explain back</strong> one line after</li>
<li>Same data as before: the 200 ad campaigns from week 3, then 50,000 Airbnb listings</li>
</ul>
</div></div>
<div class="box">
<p>Regression is the workhorse of marketing analytics. Homework 2, the Airbnb exercise, and most group projects are built on what we cover today.</p>
</div>
</section>
<section id="r-script-for-today" class="slide level2">
<h2>R script for today</h2>
<p>In the <code>code/</code> folder on the course website:</p>
<ol type="1">
<li><strong><code>w4-1-ols-class.R</code></strong>: every chart and every regression in today’s deck, with a comment above each one</li>
<li><strong><code>data/airbnb.csv</code></strong>: the Airbnb dataset used in the second half (and in the Airbnb exercise on Tuesday, Sept.&nbsp;22)</li>
</ol>
<div class="box">
<p>Download everything as one zip: <a href="https://github.com/dadepro/mkt566/raw/main/w4/w4-code.zip"><strong><code>w4-code.zip</code></strong></a>, open the folder in VS Code, and run along.</p>
</div>
</section></section>
<section>
<section id="from-a-line-to-a-model" class="title-slide slide level1 divider center">
<h1>From a Line to a Model</h1>

</section>
<section id="the-line-we-drew-last-week" class="slide level2">
<h2>The line we drew last week</h2>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1" data-code-line-numbers="3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-label="1"></a><span class="fu">ggplot</span>(marketing, <span class="fu">aes</span>(<span class="at">x =</span> youtube, <span class="at">y =</span> sales)) <span class="sc">+</span></span>
<span id="cb1-2"><a href="" aria-label="2"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb1-3"><a href="" aria-label="3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb1-4"><a href="" aria-label="4"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb1-5"><a href="" aria-label="5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb1-6"><a href="" aria-label="6"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales vs. YouTube Ad Spend"</span>,</span>
<span id="cb1-7"><a href="" aria-label="7"></a>       <span class="at">x =</span> <span class="st">"YouTube ad spend ($)"</span>,</span>
<span id="cb1-8"><a href="" aria-label="8"></a>       <span class="at">y =</span> <span class="st">"Sales (units)"</span>) <span class="sc">+</span></span>
<span id="cb1-9"><a href="" aria-label="9"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="w4-1-ols_files/figure-revealjs/line-recall-1.png" width="528"></p>
</figure>
</div>
</div>
</div></div>
<div class="smaller-80 muted">
<p>We asked R for a straight line through the points. What line is it? What could a manager do with it?</p>
</div>
</section>
<section id="a-regression-is-the-formula-for-that-line" class="slide level2">
<h2>A regression is the formula for that line</h2>
<p><span class="math display">\[\text{sales} = \beta_0 + \beta_1 \times \text{youtube}\]</span></p>
<ul>
<li>A regression <strong>predicts</strong> one variable, <span class="math inline">\(Y\)</span>, from one or more others, <span class="math inline">\(X\)</span></li>
<li><span class="math inline">\(Y\)</span> is the <strong>outcome</strong> (or dependent variable). <span class="math inline">\(X\)</span> is the <strong>predictor</strong> (or independent variable)</li>
<li>Examples:
<ul>
<li>Sales (<span class="math inline">\(Y\)</span>) as a function of ad spend (<span class="math inline">\(X\)</span>)</li>
<li>Revenue (<span class="math inline">\(Y\)</span>) as a function of review ratings (<span class="math inline">\(X\)</span>)</li>
<li>Airbnb price (<span class="math inline">\(Y\)</span>) as a function of the number of bedrooms (<span class="math inline">\(X\)</span>)</li>
<li>Income (<span class="math inline">\(Y\)</span>) as a function of years of education (<span class="math inline">\(X\)</span>)</li>
</ul></li>
</ul>
<div class="box">
<p>In general <span class="math inline">\(Y = F(X)\)</span>: <span class="math inline">\(Y\)</span> depends on <span class="math inline">\(X\)</span> <em>somehow</em>. A <strong>linear</strong> regression assumes the simplest <span class="math inline">\(F\)</span>: a straight line. Machine learning (week 10) is mostly about learning fancier <span class="math inline">\(F\)</span>’s.</p>
</div>
</section>
<section id="the-setup" class="slide level2">
<h2>The setup</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>For each row <span class="math inline">\(i\)</span> of the data (each campaign):</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_i + \epsilon_i\]</span></p>
<ul>
<li><span class="math inline">\(x_i\)</span>: the predictor (YouTube spend of campaign <span class="math inline">\(i\)</span>)</li>
<li><span class="math inline">\(y_i\)</span>: the outcome (sales of campaign <span class="math inline">\(i\)</span>)</li>
<li><span class="math inline">\(\beta_0\)</span>: the <strong>intercept</strong>, predicted <span class="math inline">\(Y\)</span> when <span class="math inline">\(X = 0\)</span></li>
<li><span class="math inline">\(\beta_1\)</span>: the <strong>slope</strong>, how much <span class="math inline">\(Y\)</span> changes when <span class="math inline">\(X\)</span> goes up by one unit</li>
<li><span class="math inline">\(\epsilon_i\)</span>: the <strong>error</strong>, the part of <span class="math inline">\(y_i\)</span> the line does not explain</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">x = youtube ($)</th>
<th style="text-align: right;">y = sales (units)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">276,120</td>
<td style="text-align: right;">26,520</td>
</tr>
<tr class="even">
<td style="text-align: right;">53,400</td>
<td style="text-align: right;">12,480</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20,640</td>
<td style="text-align: right;">11,160</td>
</tr>
<tr class="even">
<td style="text-align: right;">181,800</td>
<td style="text-align: right;">22,200</td>
</tr>
<tr class="odd">
<td style="text-align: right;">216,960</td>
<td style="text-align: right;">15,480</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="smaller-80 muted">
<p>Rows <span class="math inline">\(i = 1, \dots, 200\)</span></p>
</div>
</div></div>
</section>
<section id="the-three-pieces-on-the-chart" class="slide level2">
<h2>The three pieces, on the chart</h2>

<img data-src="w4-1-ols_files/figure-revealjs/ols-anatomy-1.png" width="768" class="r-stretch"><div class="smaller-80 muted">
<p>Every point has its own error: the vertical distance to the line. The intercept and the slope are the same for everyone.</p>
</div>
</section>
<section id="which-line" class="slide level2">
<h2>Which line?</h2>

<img data-src="w4-1-ols_files/figure-revealjs/which-line-1.png" width="960" class="r-stretch"><div class="smaller-80 muted">
<p>Both lines run through the points. The blue segments are the errors. Which line is better, and how would you <em>decide</em>?</p>
</div>
</section>
<section id="which-line-reading-it" class="slide level2">
<h2>Which line: reading it</h2>

<img data-src="w4-1-ols_files/figure-revealjs/which-line-2-1.png" width="960" class="r-stretch"><div class="smaller-90">
<ul>
<li>Square each error (so misses above and below the line both count), add them up. Smaller is better</li>
<li><strong>Ordinary least squares (OLS)</strong> picks the intercept and slope with the <strong>smallest</strong> sum of squared errors. Line B is that line, and it is what <code>geom_smooth(method = "lm")</code> drew last week</li>
<li>“Least squares” is the whole idea. Everything else today is about reading what comes out</li>
</ul>
</div>
</section>
<section id="the-sum-of-squared-errors-written-out" class="slide level2 smaller-90">
<h2>The sum of squared errors, written out</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p>For any intercept <span class="math inline">\(\beta_0\)</span> and slope <span class="math inline">\(\beta_1\)</span>, the line predicts <span class="math inline">\(\hat{y}_i = \beta_0 + \beta_1 x_i\)</span> and misses by <span class="math inline">\(\epsilon_i = y_i - \hat{y}_i\)</span>:</p>
<p><span class="math display">\[\text{SSE}(\beta_0, \beta_1) = \sum_{i=1}^{n} \epsilon_i^2
= \sum_{i=1}^{n} \left(y_i - \beta_0 - \beta_1 x_i\right)^2\]</span></p>
<ul>
<li>Every choice of <span class="math inline">\((\beta_0, \beta_1)\)</span> gives a different line, hence a different SSE. Line A and Line B are two such choices</li>
<li>OLS picks the pair that makes this sum as small as possible:</li>
</ul>
<p><span class="math display">\[(\hat{\beta}_0, \hat{\beta}_1) = \arg\min_{\beta_0,\, \beta_1} \; \text{SSE}(\beta_0, \beta_1)\]</span></p>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(y_i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\hat{y}_i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\epsilon_i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\epsilon_i^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">276,120</td>
<td style="text-align: right;">26,520</td>
<td style="text-align: right;">21,565</td>
<td style="text-align: right;">4,955</td>
<td style="text-align: right;">24,552,724</td>
</tr>
<tr class="even">
<td style="text-align: right;">53,400</td>
<td style="text-align: right;">12,480</td>
<td style="text-align: right;">10,978</td>
<td style="text-align: right;">1,502</td>
<td style="text-align: right;">2,257,299</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20,640</td>
<td style="text-align: right;">11,160</td>
<td style="text-align: right;">9,420</td>
<td style="text-align: right;">1,740</td>
<td style="text-align: right;">3,026,666</td>
</tr>
<tr class="even">
<td style="text-align: right;">181,800</td>
<td style="text-align: right;">22,200</td>
<td style="text-align: right;">17,081</td>
<td style="text-align: right;">5,119</td>
<td style="text-align: right;">26,201,361</td>
</tr>
<tr class="odd">
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
</tr>
<tr class="even">
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">3,027,644,040</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="smaller-80 muted">
<p>Line B (the OLS line), first 4 of 200 campaigns. Bottom row: the sum over all 200, the number on the previous slide.</p>
</div>
</div></div>
<div class="box">
<p>“Least squares” means exactly this: square each error, add them up, and pick the line that makes the total smallest.</p>
</div>
</section></section>
<section>
<section id="estimating-a-regression-in-r" class="title-slide slide level1 divider center">
<h1>Estimating a Regression in R</h1>

</section>
<section id="one-function-lm" class="slide level2 smaller">
<h2>One function: <code>lm()</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="" aria-label="1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube, <span class="at">data =</span> marketing)   <span class="co"># "sales as a function of youtube"</span></span>
<span id="cb2-2"><a href="" aria-label="2"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ youtube, data = marketing)

Residuals:
     Min       1Q   Median       3Q      Max 
-10063.2  -2345.4   -229.5   2480.5   8654.8 

Coefficients:
               Estimate  Std. Error t value Pr(&gt;|t|)    
(Intercept) 8439.112259  549.411528   15.36   &lt;2e-16 ***
youtube        0.047537    0.002691   17.67   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3910 on 198 degrees of freedom
Multiple R-squared:  0.6119,    Adjusted R-squared:  0.6099 
F-statistic: 312.1 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="smaller-80 muted">
<p>Find the intercept and the slope in this output. What else is in there?</p>
</div>
</section>
<section id="reading-the-output-the-estimates" class="slide level2 smaller-90">
<h2>Reading the output: the estimates</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="" aria-label="1"></a><span class="fu">coef</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       youtube 
8439.11225895    0.04753664 </code></pre>
</div>
</div>
<ul>
<li><strong>Intercept</strong> <span class="math inline">\(\beta_0 = 8{,}439\)</span>: a campaign with <strong>no</strong> YouTube spend is predicted to sell about <strong>8,400 units</strong></li>
<li><strong>Slope</strong> <span class="math inline">\(\beta_1 = 0.0475\)</span>: each additional <strong>$1</strong> on YouTube is associated with <strong>0.0475 more units</strong> sold</li>
<li>Prediction: with $100,000 on YouTube, <span class="math inline">\(8{,}439 + 0.0475 \times 100{,}000 \approx 13{,}200\)</span> units</li>
</ul>
<div class="box">
<p>Always translate the slope into <strong>business units</strong>: “one more unit of <span class="math inline">\(X\)</span> goes with <span class="math inline">\(\beta_1\)</span> more units of <span class="math inline">\(Y\)</span>”. If you cannot say it in a sentence a manager understands, you have not read the coefficient yet.</p>
</div>
</section>
<section id="the-estimate-comes-with-uncertainty" class="slide level2 smaller-90">
<h2>The estimate comes with uncertainty</h2>
<p>Our slope comes from <strong>these</strong> 200 campaigns. Another 200 would give a slightly different slope. The <strong>standard error (SE)</strong> measures how much it would move around.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="" aria-label="1"></a><span class="fu">round</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(model)), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 8439.1123   549.4115 15.3603        0
youtube        0.0475     0.0027 17.6676        0</code></pre>
</div>
</div>
<ul>
<li><code>Std. Error</code> of the slope: <strong>0.0027</strong>. The slope is pinned down to roughly <span class="math inline">\(0.0475 \pm 0.005\)</span></li>
<li><code>t value</code> = estimate / SE = <span class="math inline">\(0.0475 / 0.0027 \approx\)</span> <strong>17.7</strong>: the slope is about 18 standard errors away from zero</li>
<li><code>Pr(&gt;|t|)</code> is the <strong>p-value</strong>: here so small that it rounds to <strong>0</strong> (two slides back, <code>summary()</code> printed it as <code>&lt;2e-16</code>)</li>
</ul>
</section>
<section id="the-question-the-p-value-answers" class="slide level2 smaller-90">
<h2>The question the p-value answers</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p><strong>Hypothesis testing</strong> is a way to decide between two claims with data:</p>
<ul>
<li><span class="math inline">\(H_0\)</span> (the null): <strong>no relationship</strong>, <span class="math inline">\(\beta_1 = 0\)</span>. YouTube spend has nothing to do with sales</li>
<li><span class="math inline">\(H_1\)</span> (the alternative): <strong>there is one</strong>, <span class="math inline">\(\beta_1 \neq 0\)</span></li>
</ul>
<p>The <strong>p-value</strong> answers: <em>if <span class="math inline">\(H_0\)</span> were true, how likely is a slope at least this far from zero, just by luck?</em></p>
</div><div class="column" style="margin-left: 5%;">
<p><strong>Decision rule</strong></p>
<ul>
<li>p-value <strong>&lt; 0.05</strong>: reject <span class="math inline">\(H_0\)</span>. The coefficient is <strong>statistically significant</strong> (different from zero)</li>
<li>p-value <strong>≥ 0.05</strong>: fail to reject <span class="math inline">\(H_0\)</span>. Not enough evidence</li>
</ul>
<p>R’s stars: <code>***</code> p &lt; 0.001, <code>**</code> p &lt; 0.01, <code>*</code> p &lt; 0.05, <code>.</code> p &lt; 0.1</p>
<p><strong>Smaller SE → larger t → smaller p → stronger evidence</strong> against “no relationship”</p>
</div></div>
<div class="box">
<p>For YouTube, p is essentially 0: if spend and sales were unrelated, a slope of 0.0475 would almost never show up. So we are confident the relationship is real.</p>
</div>
</section>
<section id="significant-is-not-the-same-as-big" class="slide level2 smaller-90">
<h2>“Significant” is not the same as “big”</h2>
<p>Two separate questions about every coefficient:</p>
<ol type="1">
<li><strong>Is it different from zero?</strong> That is what the p-value answers. It depends on the size of the estimate <em>and</em> on how much data you have</li>
<li><strong>Does it matter?</strong> That is about the <strong>size</strong> of the estimate, in business units. The p-value says nothing about it</li>
</ol>
<div class="box-warn">
<p>With 50,000 rows (Airbnb, later today) almost everything is “significant”, including effects too small to care about. With 18 rows almost nothing is, including effects that are real. Read the <strong>size</strong> first, then the stars.</p>
</div>
</section>
<section id="how-good-is-the-line-r-squared" class="slide level2">
<h2>How good is the line? R-squared</h2>

<img data-src="w4-1-ols_files/figure-revealjs/r2-figure-1.png" width="960" class="r-stretch"><div class="smaller-80 muted">
<p>Forty of the 200 campaigns. Without <span class="math inline">\(X\)</span>, the best guess for every campaign is the average. How much do the errors shrink once we use the line?</p>
</div>
</section>
<section id="r-squared-reading-it" class="slide level2 smaller-90">
<h2>R-squared: reading it</h2>
<p><span class="math display">\[R^2 = 1 - \frac{\text{sum of squared errors with the line}}{\text{sum of squared errors with the mean}}
= 1 - \frac{3,027,644,040}{7,800,694,200} = 0.61\]</span></p>
<ul>
<li><strong>Multiple R-squared: 0.61</strong>. YouTube spend explains <strong>61%</strong> of the variation in sales across campaigns. The other 39% is other channels, seasonality, luck</li>
<li><span class="math inline">\(R^2\)</span> runs from 0 (the line is no better than the mean) to 1 (every point on the line)</li>
<li><strong>Residual standard error: 3,910</strong>. The typical prediction misses by about <strong>3,900 units</strong>. Same idea as <span class="math inline">\(R^2\)</span>, but in the units of <span class="math inline">\(Y\)</span></li>
<li><strong>Adjusted R-squared</strong> is <span class="math inline">\(R^2\)</span> with a small penalty for every predictor you add. Use it to compare models with different numbers of predictors</li>
</ul>
<div class="box">
<p>A low <span class="math inline">\(R^2\)</span> does not make a coefficient wrong. It says that <span class="math inline">\(X\)</span> alone leaves most of <span class="math inline">\(Y\)</span> unexplained. Whether that matters depends on your goal: <strong>prediction</strong> needs a high <span class="math inline">\(R^2\)</span>, <strong>understanding one relationship</strong> does not.</p>
</div>
</section>
<section id="the-output-decoded" class="slide level2 smaller-90">
<h2>The output, decoded</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>In the output</th>
<th>What it is</th>
<th>How to read it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Estimate</code></td>
<td><span class="math inline">\(\hat\beta\)</span>, the coefficient</td>
<td>“One more unit of <span class="math inline">\(X\)</span> goes with <span class="math inline">\(\hat\beta\)</span> more units of <span class="math inline">\(Y\)</span>”</td>
</tr>
<tr class="even">
<td><code>Std. Error</code></td>
<td>Precision of the estimate</td>
<td>Smaller is better. Would the estimate move much with new data?</td>
</tr>
<tr class="odd">
<td><code>t value</code></td>
<td>Estimate / SE</td>
<td>How many SEs from zero. Beyond ±2 is “significant”</td>
</tr>
<tr class="even">
<td><code>Pr(&gt;|t|)</code></td>
<td>p-value</td>
<td>Chance of a t this large if the true coefficient is 0</td>
</tr>
<tr class="odd">
<td><code>Residual standard error</code></td>
<td>Typical size of the error</td>
<td>In units of <span class="math inline">\(Y\)</span></td>
</tr>
<tr class="even">
<td><code>R-squared</code></td>
<td>Share of the variation in <span class="math inline">\(Y\)</span> explained</td>
<td>0 to 1</td>
</tr>
<tr class="odd">
<td><code>F-statistic</code></td>
<td>Do the predictors explain <em>anything</em> together?</td>
<td>Tiny p-value: yes</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="interpreting-the-coefficient" class="title-slide slide level1 divider center">
<h1>Interpreting the Coefficient</h1>

</section>
<section id="what-does-beta_1-tell-us" class="slide level2 smaller-90">
<h2>What does <span class="math inline">\(\beta_1\)</span> tell us?</h2>
<p><strong>All else equal</strong> (<em>ceteris paribus</em>), how much <span class="math inline">\(Y\)</span> changes when <span class="math inline">\(X\)</span> moves by one unit. What “one unit” means depends on how you wrote the model:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Equation</th>
<th>Reading of <span class="math inline">\(\beta_1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Level-level</td>
<td><span class="math inline">\(Y = \beta_0 + \beta_1 X\)</span></td>
<td>One more unit of <span class="math inline">\(X\)</span> → <span class="math inline">\(\beta_1\)</span> more <strong>units</strong> of <span class="math inline">\(Y\)</span></td>
</tr>
<tr class="even">
<td>Log-level</td>
<td><span class="math inline">\(\ln Y = \beta_0 + \beta_1 X\)</span></td>
<td>One more unit of <span class="math inline">\(X\)</span> → about <span class="math inline">\(100 \times \beta_1\)</span> <strong>percent</strong> more <span class="math inline">\(Y\)</span></td>
</tr>
<tr class="odd">
<td>Level-log</td>
<td><span class="math inline">\(Y = \beta_0 + \beta_1 \ln X\)</span></td>
<td>1% more <span class="math inline">\(X\)</span> → about <span class="math inline">\(\beta_1 / 100\)</span> more <strong>units</strong> of <span class="math inline">\(Y\)</span></td>
</tr>
<tr class="even">
<td>Log-log</td>
<td><span class="math inline">\(\ln Y = \beta_0 + \beta_1 \ln X\)</span></td>
<td>1% more <span class="math inline">\(X\)</span> → about <span class="math inline">\(\beta_1\)</span> <strong>percent</strong> more <span class="math inline">\(Y\)</span> (an <strong>elasticity</strong>)</td>
</tr>
</tbody>
</table>
<div class="smaller-80 muted">
<p>The percentage readings are approximations that work when <span class="math inline">\(\beta_1\)</span> is small (say below 0.2). The exact formula for log-level is <span class="math inline">\((e^{\beta_1} - 1) \times 100\%\)</span>.</p>
</div>
</section>
<section id="why-take-logs" class="slide level2 smaller-90">
<h2>Why take logs?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>1. Skewed variables.</strong> Price, income, sales, number of reviews: many small values, a few huge ones. You saw in week 2 that a log scale makes such distributions readable. The same is true for a regression: without the log, the few huge values pull the line around.</p>
<p><strong>2. Multiplicative relationships.</strong> A $1 price increase means something very different at $5 and at $100. In logs, the model works in <strong>percentages</strong>, which is how the relationship usually behaves.</p>
</div><div class="column" style="width:50%;">
<p><strong>3. Interpretation.</strong> Managers think in percentages: “a 10% price increase lowers demand by 8%”. A log-log coefficient <strong>is</strong> that number, the <strong>elasticity</strong>.</p>
<p><strong>Rule of thumb</strong>: log a variable that is positive and right-skewed (money, counts). Leave ratings, shares, and dummies as they are.</p>
</div></div>
<div class="box">
<p>Logs change the <strong>question</strong> you are asking, not just the fit. Level: “how many more units?”. Log: “what percent more?”. Choose the one your manager needs.</p>
</div>
</section>
<section id="the-same-relationship-three-ways" class="slide level2 smaller">
<h2>The same relationship, three ways</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="" aria-label="1"></a>m_level  <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube, <span class="at">data =</span> marketing)</span>
<span id="cb8-2"><a href="" aria-label="2"></a>m_loglev <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(sales) <span class="sc">~</span> youtube, <span class="at">data =</span> marketing)</span>
<span id="cb8-3"><a href="" aria-label="3"></a>m_loglog <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(sales) <span class="sc">~</span> <span class="fu">log</span>(youtube), <span class="at">data =</span> marketing)</span>
<span id="cb8-4"><a href="" aria-label="4"></a><span class="fu">stargazer</span>(m_level, m_loglev, m_loglog, <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb8-5"><a href="" aria-label="5"></a>          <span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"level-level"</span>, <span class="st">"log-level"</span>, <span class="st">"log-log"</span>),</span>
<span id="cb8-6"><a href="" aria-label="6"></a>          <span class="at">omit.stat =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"ser"</span>, <span class="st">"adj.rsq"</span>), <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">digits.extra =</span> <span class="dv">4</span>,</span>
<span id="cb8-7"><a href="" aria-label="7"></a>          <span class="at">no.space =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
================================================
                     Dependent variable:        
             -----------------------------------
                 sales          log(sales)      
              level-level   log-level   log-log 
                  (1)          (2)        (3)   
------------------------------------------------
youtube        0.0475***   0.000003***          
               (0.0027)    (0.0000002)          
log(youtube)                           0.3550***
                                       (0.0149) 
Constant     8,439.1120***  9.0973***  5.4781***
              (549.4115)    (0.0362)   (0.1756) 
------------------------------------------------
Observations      200          200        200   
R2              0.6119       0.6156     0.7421  
================================================
Note:                *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</section>
<section id="three-ways-reading-it" class="slide level2 smaller-90">
<h2>Three ways: reading it</h2>
<ul>
<li><strong>Level-level</strong> (column 1): $1 more on YouTube → <strong>0.0475 more units</strong></li>
<li><strong>Log-level</strong> (column 2): $1 more on YouTube → about <strong>0.0003% more sales</strong> (<span class="math inline">\(100 \times 0.000003\)</span>)</li>
<li><strong>Log-log</strong> (column 3): 1% more YouTube spend → <strong>0.36% more sales</strong>. That is the <strong>elasticity</strong> of sales with respect to YouTube spend</li>
</ul>
<div class="box">
<p><code>stargazer()</code> puts several models side by side, with standard errors in parentheses and stars for significance. This is the table format for Homework 2 and for your project. Column labels, a title, and readable variable names are the difference between a table and a wall of numbers.</p>
</div>
<div class="smaller-80 muted">
<p>Elasticities below 1 mean <span class="math inline">\(Y\)</span> responds less than proportionally: doubling YouTube spend does not double sales.</p>
</div>
</section>
<section id="more-than-one-predictor" class="slide level2 smaller-90">
<h2>More than one predictor</h2>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_{1,i} + \beta_2 x_{2,i} + \dots + \beta_k x_{k,i} + \epsilon_i\]</span></p>
<p>Everything we said still applies, with one change in the reading: each <span class="math inline">\(\beta_j\)</span> is the change in <span class="math inline">\(Y\)</span> for one more unit of <span class="math inline">\(x_j\)</span>, <strong>holding the other predictors fixed</strong>.</p>
<p>In R, add predictors to the formula with <code>+</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="" aria-label="1"></a>m_all <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube <span class="sc">+</span> facebook <span class="sc">+</span> newspaper, <span class="at">data =</span> marketing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="box">
<p>Before you look: last week’s charts showed YouTube strong, Facebook noisier, newspaper flat. Which coefficient do you expect to be largest? Which one close to zero?</p>
</div>
</section>
<section id="three-channels-at-once" class="slide level2 smaller">
<h2>Three channels at once</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="" aria-label="1"></a>m_all <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube <span class="sc">+</span> facebook <span class="sc">+</span> newspaper, <span class="at">data =</span> marketing)</span>
<span id="cb11-2"><a href="" aria-label="2"></a><span class="fu">stargazer</span>(m_yt, m_all, <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"YouTube only"</span>, <span class="st">"all three"</span>),</span>
<span id="cb11-3"><a href="" aria-label="3"></a>          <span class="at">omit.stat =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"ser"</span>, <span class="st">"adj.rsq"</span>), <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">no.space =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=========================================
                 Dependent variable:     
             ----------------------------
                        sales            
              YouTube only    all three  
                  (1)            (2)     
-----------------------------------------
youtube         0.048***      0.046***   
                (0.003)        (0.001)   
facebook                      0.189***   
                               (0.009)   
newspaper                      -0.001    
                               (0.006)   
Constant      8,439.112***  3,526.667*** 
               (549.412)      (374.290)  
-----------------------------------------
Observations      200            200     
R2               0.612          0.897    
=========================================
Note:         *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<div class="smaller-80 muted">
<p>Which channel has the largest coefficient? Which one is essentially zero?</p>
</div>
</section>
<section id="more-than-one-predictor-reading-it" class="slide level2 smaller-90">
<h2>More than one predictor: reading it</h2>
<ul>
<li><strong>Facebook</strong> has the largest coefficient: $1 more on Facebook, holding YouTube and newspaper fixed, goes with about <strong>0.19 more units</strong>. YouTube: 0.046 units per $1</li>
<li><strong>Newspaper</strong>: <span class="math inline">\(-0.001\)</span>, p-value 0.86. Once YouTube and Facebook are in the model, newspaper spend tells us <strong>nothing</strong> about sales. Remember last week’s flat newspaper panel</li>
<li><span class="math inline">\(R^2\)</span> goes from 0.61 to <strong>0.90</strong>: three channels explain 90% of the variation in sales</li>
</ul>
<div class="box">
<p>“Holding the others fixed” is what makes multiple regression useful. Campaigns that spend more on newspaper also spend more on Facebook (correlation 0.35). The single-predictor regression of sales on newspaper would give newspaper credit for Facebook’s work.</p>
</div>
</section></section>
<section>
<section id="the-airbnb-data" class="title-slide slide level1 divider center">
<h1>The Airbnb Data</h1>

</section>
<section id="the-dataset" class="slide level2 smaller">
<h2>The dataset</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="" aria-label="1"></a>airbnb <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"data/airbnb.csv"</span>)</span>
<span id="cb13-2"><a href="" aria-label="2"></a><span class="fu">names</span>(airbnb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "listing_id"          "price"               "bathrooms"           "bedrooms"           
 [5] "cancellation_policy" "guests_included"     "property_type"       "zipcode"            
 [9] "star_rating"         "reviews_count"       "city"                "room_type"          </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="" aria-label="1"></a><span class="fu">head</span>(airbnb[, .(price, bedrooms, star_rating, reviews_count, city, room_type)], <span class="dv">4</span>)  <span class="co"># a few columns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   price bedrooms star_rating reviews_count        city    room_type
   &lt;int&gt;    &lt;int&gt;       &lt;num&gt;         &lt;int&gt;      &lt;char&gt;       &lt;char&gt;
1:   238        2         5.0            79 Los Angeles  Entire home
2:    89        1         5.0           117      Austin  Entire home
3:    89        1         5.0            91       Miami Private room
4:   175        2         4.5            15      Austin  Entire home</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="" aria-label="1"></a><span class="fu">table</span>(airbnb<span class="sc">$</span>city)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       Austin        Boston   Los Angeles         Miami New York City 
        10311          6147         27611          6749            18 </code></pre>
</div>
</div>
<div class="smaller-90">
<p>50,836 listings with a nightly price, size, star rating, number of reviews, city, and room type. Four real cities and, for reasons lost to history, <strong>18 listings in New York</strong>. Keep that in mind.</p>
</div>
</section>
<section id="predict-before-you-run" class="slide level2">
<h2>Predict before you run</h2>
<p>Let’s predict <strong>price</strong> as a function of the <strong>number of reviews</strong> a listing has.</p>
<div class="box">
<p>Write down one sentence: <strong>what sign</strong> do you expect for the slope, and <strong>why</strong>?</p>
</div>
<div class="smaller-90">
<p>Two stories, opposite signs:</p>
<ul>
<li>More reviews means a popular, established listing, which can charge more (<strong>positive</strong>)</li>
<li>Cheap places get booked more often, so they collect more reviews (<strong>negative</strong>)</li>
</ul>
</div>
</section>
<section id="price-vs.-number-of-reviews" class="slide level2">
<h2>Price vs.&nbsp;number of reviews</h2>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="" aria-label="1"></a><span class="fu">ggplot</span>(airbnb, <span class="fu">aes</span>(<span class="at">x =</span> reviews_count, <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="" aria-label="2"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="" aria-label="3"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> dollar) <span class="sc">+</span></span>
<span id="cb19-4"><a href="" aria-label="4"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Price vs. Number of Reviews"</span>,</span>
<span id="cb19-5"><a href="" aria-label="5"></a>       <span class="at">x =</span> <span class="st">"Number of reviews"</span>,</span>
<span id="cb19-6"><a href="" aria-label="6"></a>       <span class="at">y =</span> <span class="st">"Nightly price"</span>) <span class="sc">+</span></span>
<span id="cb19-7"><a href="" aria-label="7"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="w4-1-ols_files/figure-revealjs/airbnb-scatter-1.png" width="528"></p>
</figure>
</div>
</div>
</div></div>
<div class="smaller-80 muted">
<p>50,836 points. What do you see? Does a straight line make sense here?</p>
</div>
</section>
<section id="price-vs.-reviews-reading-it" class="slide level2 nostretch">
<h2>Price vs.&nbsp;reviews: reading it</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="w4-1-ols_files/figure-revealjs/airbnb-scatter-2-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="smaller-90">
<ul>
<li>Both variables are <strong>heavily skewed</strong>: median price $100, a few listings at $10,000; median 8 reviews, a few above 300</li>
<li>No clear line. If anything, the pricey listings sit at <strong>low</strong> review counts, so the line tilts slightly <strong>down</strong></li>
<li>A prime candidate for logs (the exercise on Tuesday, Sept.&nbsp;22). For now, let’s see what the straight line says</li>
</ul>
</div>
</section>
<section id="the-regression" class="slide level2 smaller">
<h2>The regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="" aria-label="1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> reviews_count, <span class="at">data =</span> airbnb)</span>
<span id="cb20-2"><a href="" aria-label="2"></a><span class="fu">summary</span>(m1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ reviews_count, data = airbnb)

Residuals:
   Min     1Q Median     3Q    Max 
-145.0  -74.9  -39.5   23.3 9855.4 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   148.04066    0.90102  164.30   &lt;2e-16 ***
reviews_count  -0.34672    0.03195  -10.85   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 165.9 on 50834 degrees of freedom
Multiple R-squared:  0.002311,  Adjusted R-squared:  0.002291 
F-statistic: 117.8 on 1 and 50834 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="smaller-80 muted">
<p>Read the slope, the p-value, and the R-squared. Do they agree with the scatter plot?</p>
</div>
</section>
<section id="the-regression-reading-it" class="slide level2 smaller-90">
<h2>The regression: reading it</h2>
<ul>
<li><strong>Intercept</strong>: a listing with zero reviews is predicted to cost <strong>$148</strong></li>
<li><strong>Slope</strong> <span class="math inline">\(-0.35\)</span>: each additional review is associated with a price <strong>35 cents lower</strong>. Ten more reviews: $3.50 lower. That is tiny next to a median price of $100</li>
<li><strong>p-value &lt; 2e-16</strong>, three stars: statistically significant. With 50,000 listings, even a 35-cent slope is measured precisely</li>
<li><strong>R-squared 0.002</strong>: reviews explain <strong>0.2%</strong> of the variation in price</li>
<li><strong>Residual standard error $166</strong>: the typical miss is larger than the typical price</li>
</ul>
<div class="box-warn">
<p>Significant, and useless for prediction. The stars say the slope is not zero. The size and the <span class="math inline">\(R^2\)</span> say it does not matter. Both readings are correct, and you need both.</p>
</div>
</section>
<section id="a-table-you-can-put-in-a-report" class="slide level2 smaller">
<h2>A table you can put in a report</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="" aria-label="1"></a><span class="fu">stargazer</span>(m1, <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb22-2"><a href="" aria-label="2"></a>          <span class="at">title =</span> <span class="st">"Regression of Price on Number of Reviews"</span>,</span>
<span id="cb22-3"><a href="" aria-label="3"></a>          <span class="at">dep.var.labels =</span> <span class="st">"Nightly price (dollars)"</span>,</span>
<span id="cb22-4"><a href="" aria-label="4"></a>          <span class="at">covariate.labels =</span> <span class="st">"Number of reviews"</span>,</span>
<span id="cb22-5"><a href="" aria-label="5"></a>          <span class="at">omit.stat =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"ser"</span>, <span class="st">"adj.rsq"</span>), <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">no.space =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression of Price on Number of Reviews
=============================================
                      Dependent variable:    
                  ---------------------------
                    Nightly price (dollars)  
---------------------------------------------
Number of reviews          -0.35***          
                            (0.03)           
Constant                   148.04***         
                            (0.90)           
---------------------------------------------
Observations                50,836           
R2                           0.002           
=============================================
Note:             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<div class="smaller-80 muted">
<p>Same numbers as <code>summary()</code>, laid out for a reader. Standard errors in parentheses, stars for significance, <span class="math inline">\(N\)</span> and <span class="math inline">\(R^2\)</span> at the bottom.</p>
</div>
</section></section>
<section>
<section id="categorical-predictors" class="title-slide slide level1 divider center">
<h1>Categorical Predictors</h1>

</section>
<section id="text-in-a-regression" class="slide level2 smaller-90">
<h2>Text in a regression?</h2>
<p>City is a word, not a number. R handles this with a <strong>factor</strong>: a categorical variable stored as numbers with labels attached.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="" aria-label="1"></a>city <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Miami"</span>, <span class="st">"Austin"</span>, <span class="st">"Miami"</span>, <span class="st">"Boston"</span>))</span>
<span id="cb24-2"><a href="" aria-label="2"></a>city</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Miami  Austin Miami  Boston
Levels: Austin Boston Miami</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="" aria-label="1"></a><span class="fu">as.integer</span>(city)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 1 3 2</code></pre>
</div>
</div>
<ul>
<li>R stores 1, 2, 3 and shows you the labels. Levels are sorted alphabetically unless you say otherwise</li>
<li><code>lm()</code> converts a text column into a factor automatically. But <strong>what does a slope on “city” mean?</strong> Let’s look</li>
</ul>
</section>
<section id="price-by-city" class="slide level2 smaller">
<h2>Price by city</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="" aria-label="1"></a>m_city <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> city, <span class="at">data =</span> airbnb)</span>
<span id="cb28-2"><a href="" aria-label="2"></a><span class="fu">stargazer</span>(m_city, <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">title =</span> <span class="st">"Regression of Price on City"</span>,</span>
<span id="cb28-3"><a href="" aria-label="3"></a>          <span class="at">dep.var.labels =</span> <span class="st">"Nightly price (dollars)"</span>, <span class="at">omit.stat =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"ser"</span>, <span class="st">"adj.rsq"</span>),</span>
<span id="cb28-4"><a href="" aria-label="4"></a>          <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">no.space =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression of Price on City
=============================================
                      Dependent variable:    
                  ---------------------------
                    Nightly price (dollars)  
---------------------------------------------
cityBoston                 -17.60***         
                            (2.67)           
cityLos Angeles            -36.77***         
                            (1.91)           
cityMiami                  -40.93***         
                            (2.59)           
cityNew York City           -28.17           
                            (39.03)          
Constant                   169.95***         
                            (1.63)           
---------------------------------------------
Observations                50,836           
R2                           0.01            
=============================================
Note:             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<div class="smaller-80 muted">
<p>Five cities, four coefficients. Where did Austin go? And what is the constant?</p>
</div>
</section>
<section id="price-by-city-reading-it" class="slide level2 smaller-90">
<h2>Price by city: reading it</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p>Behind the scenes, R turns city into <strong>dummy variables</strong> (0/1), one per city, and <strong>drops one</strong>: the <strong>base level</strong>, Austin (first alphabetically).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Listing</th>
<th>City</th>
<th>Boston</th>
<th>LA</th>
<th>Miami</th>
<th>NYC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Austin</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>Boston</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>LA</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>4</td>
<td>Miami</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>5</td>
<td>NYC</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:58%;">
<ul>
<li>The <strong>constant</strong> ($169.95) is the average price in the base city, <strong>Austin</strong></li>
<li>Each coefficient is the <strong>difference from Austin</strong>: Boston $17.60 cheaper, Los Angeles $36.77 cheaper, Miami $40.93 cheaper. All three precisely estimated (three stars)</li>
<li><strong>New York</strong>: $28 cheaper, p-value 0.47, <strong>not</strong> significant. Not because New York is like Austin, but because there are <strong>18</strong> listings: the standard error is $39, versus $2–3 for the other cities</li>
</ul>
<div class="box-warn">
<p>“Not significant” can mean “no difference” or “not enough data”. Look at the standard error and the group size before you conclude anything.</p>
</div>
</div></div>
</section>
<section id="choosing-the-base-level" class="slide level2 smaller">
<h2>Choosing the base level</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="" aria-label="1"></a>airbnb<span class="sc">$</span>city <span class="ot">&lt;-</span> <span class="fu">relevel</span>(<span class="fu">factor</span>(airbnb<span class="sc">$</span>city), <span class="at">ref =</span> <span class="st">"Los Angeles"</span>)</span>
<span id="cb30-2"><a href="" aria-label="2"></a>m_city2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> city, <span class="at">data =</span> airbnb)</span>
<span id="cb30-3"><a href="" aria-label="3"></a><span class="fu">stargazer</span>(m_city, m_city2, <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"base: Austin"</span>, <span class="st">"base: Los Angeles"</span>),</span>
<span id="cb30-4"><a href="" aria-label="4"></a>          <span class="at">dep.var.labels =</span> <span class="st">"Nightly price (dollars)"</span>, <span class="at">omit.stat =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"ser"</span>, <span class="st">"adj.rsq"</span>),</span>
<span id="cb30-5"><a href="" aria-label="5"></a>          <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">no.space =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
================================================
                       Dependent variable:      
                  ------------------------------
                     Nightly price (dollars)    
                  base: Austin base: Los Angeles
                      (1)             (2)       
------------------------------------------------
cityAustin                         36.77***     
                                    (1.91)      
cityBoston         -17.60***       19.18***     
                     (2.67)         (2.33)      
cityLos Angeles    -36.77***                    
                     (1.91)                     
cityMiami          -40.93***        -4.16*      
                     (2.59)         (2.25)      
cityNew York City    -28.17          8.61       
                    (39.03)         (39.01)     
Constant           169.95***       133.17***    
                     (1.63)         (1.00)      
------------------------------------------------
Observations         50,836         50,836      
R2                    0.01           0.01       
================================================
Note:                *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<div class="smaller-80 muted">
<p>Same data, same fit (same <span class="math inline">\(R^2\)</span>), different comparison. Pick the base your reader cares about: the largest group, or the “status quo” option.</p>
</div>
</section></section>
<section>
<section id="regression-is-still-not-causation" class="title-slide slide level1 divider center">
<h1>Regression Is Still Not Causation</h1>

</section>
<section id="what-the-coefficient-does-and-does-not-say" class="slide level2 smaller-90">
<h2>What the coefficient does and does not say</h2>
<p>Price is $37 lower in Los Angeles than in Austin. Reviews go with slightly lower prices. Facebook spend goes with more sales. All of these are <strong>associations</strong>. None of them tells you what happens if you <em>change</em> <span class="math inline">\(X\)</span>.</p>
<ul>
<li>A regression holds fixed <strong>only the predictors you put in</strong>. Everything you left out (listing quality, neighborhood, season) is still free to move with <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> at the same time</li>
<li>Adding predictors helps (newspaper’s “effect” vanished once Facebook was in). It does not settle the question. Weeks 11–12 are about designs that do</li>
</ul>
<div class="box">
<p>Words matter. Write “a one-unit increase in <span class="math inline">\(X\)</span> <strong>is associated with</strong> a <span class="math inline">\(\beta_1\)</span> change in <span class="math inline">\(Y\)</span>”, not “<span class="math inline">\(X\)</span> <strong>causes</strong> <span class="math inline">\(Y\)</span>”, unless you have a reason to believe it, and can say why.</p>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 divider center">
<h1>Wrap-up</h1>

</section>
<section id="whats-next" class="slide level2">
<h2>What’s next</h2>
<ul>
<li><strong>Tuesday, Sept.&nbsp;22</strong>: <strong>logit</strong>, regression for yes/no outcomes (will a listing get booked? will a customer churn?). Then the <strong>Airbnb exercise</strong> on your laptop: logs, more predictors, city and room type, and where you would buy a property. Bring the week 1 setup working</li>
<li><strong>Homework 2</strong> (due Thursday, Oct.&nbsp;8): the same tools on a box-office dataset, OLS and logit, with <code>stargazer</code> tables and an executive memo</li>
</ul>
<div class="box">
<p>Before Tuesday, run today’s script on the Airbnb data and try one thing on your own: replace <code>reviews_count</code> with <code>bedrooms</code> in <code>m1</code>. Predict the slope first, then explain back what the intercept means.</p>
</div>
</section>
<section id="wrap-up-1" class="slide level2">
<h2>Wrap-up</h2>
<div class="box">
<p>Code and data to reproduce today’s regressions, on the course website:</p>
<ul>
<li><a href="https://github.com/dadepro/mkt566/raw/main/w4/w4-code.zip"><strong><code>w4-code.zip</code></strong></a>: one-click download of everything below</li>
<li><a href="https://github.com/dadepro/mkt566/blob/main/w4/code/w4-1-ols-class.R"><strong><code>w4-1-ols-class.R</code></strong></a>: every chart and regression shown today</li>
<li><a href="https://github.com/dadepro/mkt566/blob/main/w4/code/data/airbnb.csv"><strong><code>data/airbnb.csv</code></strong></a>: the Airbnb dataset (also used in the Airbnb exercise on Tuesday, Sept.&nbsp;22)</li>
</ul>
</div>
<div class="smaller-80 muted">
<p>Required reading: Chapter <a href="https://bookdown.org/content/6ef13ea6-4e86-4566-b665-ebcd19d45029/secondarydata.html#linear-regression">3.4</a> of <em>R for Marketing Students</em>. Optional: <a href="https://raw.githack.com/dadepro/mkt-615/main/lectures/08-regression/08-regressions.html#1">Lecture 6 of Data Storytelling for Marketers</a> and Chapter 7 of <em>R for Marketing Research and Analytics</em>.</p>
</div>
</section></section>
<section id="questions" class="title-slide slide level1 divider center">
<h1>Questions?</h1>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>MKT 566 · Marketing Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="w4-1-ols_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="w4-1-ols_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="w4-1-ols_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="w4-1-ols_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="w4-1-ols_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="w4-1-ols_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="w4-1-ols_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="w4-1-ols_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="w4-1-ols_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="w4-1-ols_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
                // target, if specified
                link.setAttribute("target", "_blank");
                if (link.getAttribute("rel") === null) {
                  link.setAttribute("rel", "noopener");
                }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>